### ISSUE TITLE
Symfony 4.x support?

### ISSUE THREAD

**Issue by janwebdev** [PUGX/PUGXI18nBundle#8]
Hi. Thanks for nice and usefull bundle.
Will there be support for installation for latest Symfony 4.x on PHP 7.2.*??
Via recipe or somehow... ))
Or may be there is a way for now to include bundle in project based on Symfony 4.x ??

**Comment by janwebdev** [comment]
Thanks, it can be installed now. Is there in plans stable version with symfony 4.1.
For now it is hard to update project with "composer update command":

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pugx/i18n-bundle dev-master requires symfony/framework-bundle dev-master -> no matching package found.
    - pugx/i18n-bundle master requires symfony/framework-bundle dev-master -> no matching package found.
    - Installation request for pugx/i18n-bundle dev-master -> satisfiable by pugx/i18n-bundle[master].
```

**Comment by garak** [comment]
Here it is: https://github.com/PUGX/PUGXI18nBundle/releases/tag/v4.1.0
